# docker-compose.yml
version: '3.8'

services:
  mysql:
    image: mysql:9.6
    pull_policy: never          # ← Dùng image local, không pull từ Docker Hub
    container_name: homestay_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD ROOT}
      MYSQL_DATABASE: homestay_db
      MYSQL_USER: homestay_user
      MYSQL_PASSWORD: ${PASSWORD USER}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - homestay_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    driver: local

networks:
  homestay_network:
    driver: bridge